### ISSUE TITLE
text2vec-ollama

### ISSUE THREAD

**Issue by zaforcan** [antas-marcin/weaviate-ollama-rag-sample#1]
in docker-compose file there is a module named "tex2vec-ollama"  but not used anywhere.
also in docker-compose file it's not have a image adress or something else..

with "docker exec -i text2vec-ollama /bin/ollama pull nomic-embed-text"  command,  i have an error like "there is no module named text2vec-ollama"

**Comment by zaforcan** [comment]
```
`version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.0
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama, generative-ollama'
      CLUSTER_HOSTNAME: 'node1'`
```
this is my docker-compose.yml file




```
from weaviate.classes.config import Configure, Property, DataType

client.collections.create(
    "Article",
    vectorizer_config=Configure.Vectorizer.text2vec_ollama(
        api_endpoint="http://host.docker.internal:11434",
        model="nomic-embed-text",
        ),
    generative_config=Configure.Generative.ollama(
        api_endpoint="http://host.docker.internal:11434",
        model="llama3"),
    properties=[
        Property(name="title", data_type=DataType.TEXT),
        Property(name="body", data_type=DataType.TEXT),
    ]
)

```
and this is my collection creating way..  it's working for me
